# Generated by Django 4.1.2 on 2022-11-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order_num',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
