# Generated by Django 4.1.2 on 2022-11-21 16:39

from django.db import migrations, models
import quiz.validators


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_order_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='order_num',
            field=models.PositiveSmallIntegerField(validators=[quiz.validators.order_num_count]),
        ),
    ]
